{
  "props": {
    "singleton": true,
    "author": "merkus",
    "description": "Работа с iptables",
    "version": "0.1"
  },
  "components": {
    "fileChooser": {
      "type": "script\\FileChooserScript",
      "x": 48.0,
      "y": 16.0,
      "props": {
        "saveDialog": true,
        "filterName": "Все файлы",
        "filterExtensions": "*.*",
        "filterAny": "0",
        "inputNode": "",
        "actionNode": ""
      }
    },
    "fileChooserAlt": {
      "type": "script\\FileChooserScript",
      "x": 160.0,
      "y": 16.0,
      "props": {
        "saveDialog": false,
        "filterName": "Все файлы",
        "filterExtensions": "*.*",
        "filterAny": "0",
        "inputNode": "",
        "actionNode": ""
      }
    }
  }
}